services:
  postgres:
    image: postgres:16
    container_name: sklep_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sklep
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d:z
    restart: unless-stopped

volumes:
  postgres_data:
